[phases.setup]
nixPkgs = ['nodejs_20', 'php83', 'php83Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci',
    'npm run build'
]

[start]
cmd = 'bash railway-start.sh'